version: "3.8"

volumes:
  postgres_data_dev: {}

services:
  db-local:
    image: postgres:15.2-alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  db-test:
    image: postgres:15.2-alpine3.17
    ports:
      - "5544:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
