version: '3'

vars:
  DIRS: src test

dotenv: ['.env.local']

tasks:
  # Backend commands
  deps:
    desc: Install all dev deps
    cmds:
      - clojure -P -X:dev:test:outdated:shadow:cljs

  test:
    desc: Run tests
    cmds:
      - clojure -X:dev:test

  fmt-check:
    desc: Check code formatting
    cmds:
      - cljstyle check --report {{ .DIRS }}

  fmt:
    desc: Fix code formatting
    cmds:
      - cljstyle fix --report {{ .DIRS }}

  lint-init:
    desc: Linting project's classpath
    cmds:
      - clj-kondo --parallel --dependencies --copy-configs --lint {{ .DIRS }}
    vars:
      DIRS:
        sh: clojure -Spath

  lint:
    desc: Linting project's code
    cmds:
      - clj-kondo --parallel --lint {{ .DIRS }}

  outdated-check:
    desc: Check outdated deps versions
    cmds:
      - clojure -M:outdated {{ .CLI_ARGS }}

  outdated:
    desc: Upgrade outdated Clojure deps versions
    cmds:
      - task: outdated-check
        vars: { CLI_ARGS: '--upgrade --force' }

  # Frontend commands
  shadow:
    desc: Run shadow-cljs commands
    internal: true
    cmds:
      - clojure -M:dev:cljs:shadow {{ .CLI_ARGS }}

  js-watch:
    desc: Run shadow-cljs commands to build frontend in watch mode
    internal: true
    cmds:
      - task: shadow
        vars: { CLI_ARGS: 'watch app'}

  css:
    desc: Build css in dev mode
    internal: true
    vars:
      OUTPUT_FILE: '{{ .OUTPUT_FILE | default "output.css" }}'
    cmds:
      - npx tailwindcss -i ./resources/public/css/input.css -o ./resources/public/css/{{.OUTPUT_FILE}} {{ .CLI_ARGS }}

  css-watch:
    desc: Build css in watch mode
    internal: true
    cmds:
      - task: css
        vars: { CLI_ARGS: '--watch' }

  css-prod:
    desc: Build css in prod mode
    cmds:
      - task: css
        vars:
          OUTPUT_FILE: output-prod.css
          CLI_ARGS: '--minify'

  ui:
    desc: Build js and css in watch mode for local development
    deps: [css-watch, js-watch]

  # Local docker compose commands
  up:
    desc: Run docker services for local development
    cmds:
      - docker compose up -d db-local db-test

  migrations:
    desc: Manage db migrations
    cmds:
      - clojure -X:migrations {{ .CLI_ARGS }}

  # Production build
  build:
    desc: Build uberjar
    cmds:
      - task: css-prod
      - task: shadow
        vars: { CLI_ARGS: 'release app' }
      - clojure -T:build build
