name: Checks

on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Cache Clojure dev dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-dev-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure-dev

#      - name: Restore cached clojure dev deps
#        id: cache-restore-clojure-dev-deps
#        uses: actions/cache/restore@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-clojure-dev-${{ hashFiles('**/deps.edn') }}
#          restore-keys: ${{ runner.os }}-clojure-dev

      - name: Install Clojure dev deps
        run: task deps

#      - name: Save cached Clojure dev deps
#        uses: actions/cache/save@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ steps.cache-restore-clojure-dev-deps.outputs.cache-primary-key }}

  fmt:
    runs-on: ubuntu-latest
    needs: [ deps ]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Fmt
        run: task fmt-check

  lint:
    runs-on: ubuntu-latest
    needs: [ deps ]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Restore cached clojure dev deps
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-dev-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure-dev

      - name: Lint
        run: task lint-init && task lint

  outdated:
    runs-on: ubuntu-latest
    needs: [ deps ]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Restore cached clojure dev deps
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-dev-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure-dev

      - name: Outdated deps
        run: task outdated-check

#      TODO: run tests!
