name: Deploy


on:
  pull_request:
    branches: [ master ]

jobs:
#  lint_fmt:
#    uses: ./.github/workflows/_lint_fmt.yaml

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          MISE_DISABLE_TOOLS: node,cljstyle,lefthook,ruby,clj-kondo

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-outdated-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-outdated

      - name: Outdated deps
        run: task outdated-check
